### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by WilliamAnthony** [Castaglia/proftpd-mod_digest#27]
```
libtool: compile:  gcc -DHAVE_CONFIG_H -DLINUX -I.. -I../include -O2 -Wall -DPR_SHARED_MODULE -c mod_digest.c  -fPIC -DPIC -o .libs/mod_digest.o
mod_digest.c: In function ‘digest_mod_unload_ev’:
mod_digest.c:2683:5: error: too few arguments to function ‘pr_event_unregister’
     pr_event_unregister(&digest_module, NULL);
     ^
In file included from ../include/conf.h:455:0,
                 from mod_digest.c:30:
../include/event.h:71:5: note: declared here
 int pr_event_unregister(module *m, const char *event,
     ^
make[1]: *** [mod_digest.la] Error 1

```

edit the line 2683 from pr_event_unregister(&digest_module, NULL); to pr_event_unregister(&digest_module, NULL, NULL); seems OK, but I'm not sure if it's the right solution.

**Comment by Castaglia** [comment]
The `mod_digest` module is now distributed/bundled with the [ProFTPD source code](https://github.com/proftpd/proftpd). There, the necessary changes for building with newer ProFTPD (and OpenSSL) versions has been done.
