### ISSUE TITLE
Compilation Error .so File

### ISSUE THREAD

**Issue by bjarneeins** [Castaglia/proftpd-mod_digest#29]
I am currently trying to get an .so file of mod_digest.

Therefore i am running the following Command in my proftpd file Folder:

./configure --enable-dso --enable-openssl --with-shared=mod_digest

Configuring works fine but when executing "make" the following output is being shown:

/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
Makefile:34: recipe for target 'mod_digest.la' failed
make[1]: *** [mod_digest.la] Error 1
make[1]: Verzeichnis „/usr/src/proftpd-1.3.6/modules“ wird verlassen
Makefile:39: recipe for target 'modules' failed

I am pretty sure the issue is on my side but i am not able to find it..

**Comment by Castaglia** [comment]
The `mod_digest` module is now distributed/bundled with the [ProFTPD source code](https://github.com/proftpd/proftpd). There, the necessary changes for building with newer ProFTPD (and OpenSSL) versions has been done.
