### ISSUE TITLE
openssl 1.1.0 support

### ISSUE THREAD

**Issue by wmjasonward** [Castaglia/proftpd-mod_digest#30]
Are there plans to support the openssl 1.1.0 api changes so it can be used with > 1.3.6rc2?

**Comment by Castaglia** [comment]
The `mod_digest` module is now distributed/bundled with the [ProFTPD source code](https://github.com/proftpd/proftpd).  There, the necessary changes for building with newer ProFTPD (and OpenSSL) versions has been done.
